name: ssn_coding_club
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.1
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  glassmorphism_ui: ^0.2.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.3
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
